- name: Testing capacity role operations
  hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - dellemc.powermax

  vars:
    unispherehost: 'your_unisphere_host_url'
    universion: 'version_of_the_unisphere'
    verifycert: False
    user: 'your_username'
    password: 'your_password'
    size: 10
    cap_unit: 'GB'

  tasks:
  - name: Get the Serial Number and Assigned Pool with no value for service_level
    include_role:
      name: capacity_role
